### ISSUE TITLE
height argument to output_widget does nothing

### ISSUE THREAD

**Issue by jacksimpsoncartesian** [rstudio/py-shinywidgets#106]
* shinywidgets version: 0.2.1
* Python version: 3.10
* Operating System: Ubuntu

### Description

Within a shiny app, setting the height argument in output_widget doesn't actually change the height

### What I Did

This code works, but shiny does not modify the height of the widget

```
output_widget("map", width='800px', height='100px'),
```

**Comment by cpsievert** [comment]
Currently you need to use ipywidgets layout API, which effectively sizes the contents of the `output_widget()` container. So, if you prefer to control sizing through fixed sizes in `output_widget()`, consider setting `layout.height = "100%"` (and `layout.width = "100%"` if need be). 

Here's an actual [example with `ipyleaflet`](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACGnAGzigDMvWoAZxYAZADoQejYjBYALMjA5lixDsLoNmLQoMESpMloLk0I2NvSasAgujwtG3QmRoA3OA6cQAJnEYOAK40BtKyJmbYAO40PgDmcGQaVtrEgWSo6QD6MfGJXs6uHllOUD4FcTSCFIw5sQlkEhJoqFnBLAC8LMFYUAlZfME+ABQSLOMsaRnZuQ2jYDBoYvjycDRxCh3LABwADLuoAB7LAJQSZxASfjzG-h6Mw2aZZA5Tzw6CcHo0pCeIYxMAMQsACSEBorigHBoAC84CwoL4WD4qqgOFALFE5JQWGRsbdvqRjGQoMxhMMAIwXCYsRaoTqiDAAWTQw0IlBqHWGAFYKRgACwAdgAbNtuQAmBwAWl2GH2u25+xODhhqhgHQpkuMhGkHA4OWxcH1qpkHQAKoxAnBqUCWDYfD4EciqiSIOztVC4ADxnSMGUfFkSORdcMRBguLx+BgAMqET0AYVIZBDDEEEJ+EC2YAARsQyColHAeI0wCcbT60OGMVMMNj1goGcsKfsAKTLb20yvo7A13J4xtgZu7NtgDtOSrVfx1PJkeZ05YOOkXJrQdAMuyoYYtNo0D53fwXMAAXwAukA)

**Comment by jacksimpsoncartesian** [comment]
Thanks so much!

**Comment by jacksimpsoncartesian** [comment]
Works perfectly
