### ISSUE TITLE
Widgets don't load sometimes

### ISSUE THREAD

**Issue by wch** [rstudio/py-shinywidgets#43]
With this [example app](https://pyshiny.netlify.app/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAF21QWULgA9D8wBjAewguaTADMAnBmAAgGcAFgEsI2XsJioGnQrwBUAHQhceEnENHjJ02QuU6Zc4TgDuwgCYBzOIX68o9k9mWq+z89dv8Mnm3d9LfwkpI14AdSDbZRjodAB9AFdhXgBeXmSsKBt49gAbZIsACgZEwlQy+L9bIsUwfjzLOE46vF5BOGErQUJUuoBWAAZUSjqASjbM0vLKimpasAA3KAK4cbHY5Qs4dgFmxeai0QrCRF4ASQgT-jbpk7OAeTLrtv44fn5hJjOAZXfPphjRDKXig3iLNK8ThwKB0QjCA4YABqK0ScCKADkmHANhAwQJIc4MJdCD9GttOLU8fiwctVql+ngQTTQTBRKlBkzqSyYFBKKkAIyc5ks-gUVCCrks0Hbfh0TgmeFMPpgAAq71OrRFNMYzFEiVK-CSqAsUAoqVVnDRUulMmEcGYZq+EBVgjtAC8mIQVlruTToVALNNUgAxFZvG2g3HagDEvFVInsQlKeQsvFQCuYvCYvDgB044jojQdhAAtJ9trw6IIoBAbLxCAwGx0BOTmtqfAwAEZvTgHIp5WBd01Vmt1uBnRYYN6EIrV2s2DAQOCmCa8Op0tHjWL4gACdzKRVxe+hEApVSis+PYO2uwaTUpQO1+OhhESnDx-B3YP3z0P19BXdT3POYr21W9wVRdEnz9F9bHfPF2DqBM4Eg1Zs12QgW3vCkJH4M4QEWI8AF86k2OJUEhABBdAijQVAkmEV59maNpti7RIrAtK0cWUMBiIAXSAA), the slider sometimes shows up and sometimes doesn't. I think it's possible that there's some sort of timing issue. Is it possible that it's trying to render the widget before some of the relevant JS code has been initialized?

**Comment by cpsievert** [comment]
This issue has surfaced (and can be replicated consistently with `shiny run examples/outputs/app.py` -- note how the widget doesn't render on initial load) since `py-shiny`'s JS no longer includes https://github.com/rstudio/shiny/issues/3635
