### ISSUE TITLE
"hello world" some reactive output doesn't render

### ISSUE THREAD

**Issue by datakid** [rstudio/py-shinywidgets#56]
I followed the directions for [troubleshooing ipywidgets](https://github.com/rstudio/py-shinywidgets#troubleshooting) and tried the 'hello world' app as requested. 

Using py 3.10.7:

`pipenv install uvicorn shiny shinywidgets`

I can see and use the input slider, and the value changes. But I'm not seeing any text that says

> The value of the slider is: X

https://github.com/rstudio/py-shinywidgets/blob/80109da5d2e7dc25655c02d2c459b66f39d95f6d/examples/ipywidgets/app.py#L25-L29

I found [this bug](https://github.com/rstudio/py-shinywidgets/issues/15), but it's about `@render_ipywidgets` - not `reactive.Effect()` - and it's closed.

**Comment by cpsievert** [comment]
What version of ipywidgets do you have? This could be #40

**Comment by datakid** [comment]
That looks right:

```
pip list|grep ipyw
ipywidgets         8.0.2
```

**Comment by cpsievert** [comment]
> should I pipenv install ipywidgets~=7.0?

For right now I'll think you'll need that, but I'm hoping to fix it this week

**Comment by datakid** [comment]
All good, I'm new to the whole thing, I'll just use `matplotlib`.

**Comment by pckroon** [comment]
Hi, I'm running into the same issue with ipywidgets==7.7.2 and shinywidgets==0.1.2.

**Comment by cpsievert** [comment]
AFAIK, the most recent release of shinywidgets should work with recent versions of ipywidgets...please open a new issue you're still having issues
