### ISSUE TITLE
Suggestion - Support for bqplot and plotly

### ISSUE THREAD

**Issue by mfesan36** [rstudio/py-shinywidgets#58]
It would be great if you could support rendering bqplot: https://github.com/bqplot/bqplot.  
The same goes for plotly, I could not find any plotly example which is supported in R version.
Thanks

**Comment by cpsievert** [comment]
Both of these projects are supported, see for example https://github.com/rstudio/py-shinywidgets/blob/main/examples/outputs/app.py

**Comment by mfesan36** [comment]
This is great!, thanks for pointing me to the example. By any chance does pyshiny support dark theme?

**Comment by cpsievert** [comment]
There's no 1st class support for dark theme at the moment (although you could probably hack some custom CSS together). Feel free to open an issue over at https://github.com/rstudio/py-shiny
